#!/bin/bash
############################################################
# CCM Configuration Export Script
# 功能: 导出当前ccm配置用于其他机器(如macOS)使用
# 作者: Generated by Claude Code
# 版本: 1.0.0
############################################################

# 输出文件
OUTPUT_FILE="${1:-ccm-export.tar.gz}"
TEMP_DIR=$(mktemp -d)

echo "🔄 正在导出CCM配置..."

# 创建临时目录结构
mkdir -p "$TEMP_DIR/.local/share/ccm"
mkdir -p "$TEMP_DIR/.config"

# 1. 复制ccm脚本
if [ -f ~/.local/share/ccm/ccm.sh ]; then
    cp ~/.local/share/ccm/ccm.sh "$TEMP_DIR/.local/share/ccm/"
    echo "✅ 已复制 ccm.sh"
else
    echo "❌ 未找到 ccm.sh"
    rm -rf "$TEMP_DIR"
    exit 1
fi

# 2. 复制语言文件(如果存在)
if [ -d ~/.local/share/ccm/lang ]; then
    cp -r ~/.local/share/ccm/lang "$TEMP_DIR/.local/share/ccm/"
    echo "✅ 已复制语言文件"
fi

# 3. 复制配置文件并脱敏
if [ -f ~/.ccm_config ]; then
    # 创建脱敏版本的配置文件
    cat ~/.ccm_config | sed -E \
        -e 's/(DEEPSEEK_API_KEY=)sk-[a-zA-Z0-9]+/\1sk-YOUR-DEEPSEEK-KEY/' \
        -e 's/(GLM_API_KEY=)[a-zA-Z0-9.]+/\1YOUR-GLM-KEY/' \
        -e 's/(KIMI_API_KEY=)[a-zA-Z0-9]+/\1YOUR-KIMI-KEY/' \
        -e 's/(ZHIHUI_API_KEY=)sk-[a-zA-Z0-9]+/\1sk-YOUR-ZHIHUI-KEY/' \
        -e 's/(KIRO_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-KIRO-KEY/' \
        -e 's/(CLAUDE_API_KEY=)sk-[a-zA-Z0-9]+/\1sk-YOUR-CLAUDE-KEY/' \
        -e 's/(ARK_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-ARK-KEY/' \
        -e 's/(QWEN_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-QWEN-KEY/' \
        -e 's/(PPINFRA_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-PPINFRA-KEY/' \
        -e 's/(LONGCAT_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-LONGCAT-KEY/' \
        -e 's/(MINIMAX_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-MINIMAX-KEY/' \
        -e 's/(KAT_API_KEY=)[a-zA-Z0-9-]+/\1YOUR-KAT-KEY/' \
        > "$TEMP_DIR/.ccm_config"
    echo "✅ 已复制配置文件 (API密钥已脱敏)"
fi

# 4. 复制账号文件(如果存在)，但不包含实际凭证
if [ -f ~/.ccm_accounts ]; then
    # 仅复制结构，不包含实际的base64编码凭证
    echo "{}" > "$TEMP_DIR/.ccm_accounts"
    echo "⚠️  账号文件已初始化为空 (安全考虑)"
fi

# 5. 创建README
cat > "$TEMP_DIR/README.md" << 'EOF'
# CCM Configuration Export

这是从Linux机器导出的CCM配置文件包。

## 安装步骤

### 1. 解压文件
```bash
tar -xzf ccm-export.tar.gz
cd ccm-export
```

### 2. 安装ccm脚本
```bash
# 创建目录
mkdir -p ~/.local/share/ccm

# 复制ccm脚本
cp .local/share/ccm/ccm.sh ~/.local/share/ccm/
chmod +x ~/.local/share/ccm/ccm.sh

# 复制语言文件(如果存在)
if [ -d .local/share/ccm/lang ]; then
    cp -r .local/share/ccm/lang ~/.local/share/ccm/
fi
```

### 3. 配置API密钥
```bash
# 复制配置文件模板
cp .ccm_config ~/.ccm_config

# 使用编辑器填入你的API密钥
vim ~/.ccm_config  # 或使用 nano, code 等编辑器
```

### 4. 添加别名到shell配置
在 `~/.zshrc` 或 `~/.bashrc` 中添加:
```bash
# CCM - Claude Code Model Switcher
alias ccm='~/.local/share/ccm/ccm.sh'
```

### 5. 重新加载shell配置
```bash
source ~/.zshrc  # 或 source ~/.bashrc
```

### 6. 测试安装
```bash
ccm status
```

## macOS特殊说明

在macOS上，ccm支持Claude Pro账号管理，使用Keychain存储凭证:

```bash
# 保存当前Claude Pro账号
ccm save-account personal

# 切换账号
ccm switch-account work

# 列出所有账号
ccm list-accounts
```

## 常用命令

```bash
# 切换到Deepseek
eval "$(ccm deepseek)"

# 切换到Claude Haiku
eval "$(ccm haiku)"

# 查看当前状态
ccm status

# 编辑配置
ccm config
```

## 注意事项

- 所有API密钥已被脱敏，需要手动填入
- KIRO配置使用的是Tailscale地址，macOS上可能需要调整
- 建议根据实际网络环境调整BASE_URL配置
EOF

# 6. 打包
cd "$TEMP_DIR/.."
BASENAME=$(basename "$TEMP_DIR")
tar -czf "$OUTPUT_FILE" -C "$TEMP_DIR/.." "$BASENAME"
mv "$OUTPUT_FILE" "$OLDPWD/"
rm -rf "$TEMP_DIR"

echo ""
echo "✅ 导出完成!"
echo "📦 输出文件: $OUTPUT_FILE"
echo ""
echo "使用方法:"
echo "  1. 将 $OUTPUT_FILE 传输到macOS机器"
echo "  2. 解压: tar -xzf $OUTPUT_FILE"
echo "  3. 参考README.md进行安装"
